#!/usr/bin/bash

#SBATCH --job-name=da-ilcc
#SBATCH --output="/net/talisker/home/benos/mae117/Documents/research/dennis/containers/domain_adaptation/seqadapt/logs/da-ilcc_%j.out"
#SBATCH --error="/net/talisker/home/benos/mae117/Documents/research/dennis/containers/domain_adaptation/seqadapt/logs/da-ilcc_%j.err"
#SBATCH --gres=gpu:1
#SBATCH --partition=dept_gpu

ROOT="/net/talisker/home/benos/mae117/Documents/research/dennis/containers/domain_adaptation/seqadapt/src"

Rscript "$ROOT/vae-ilcc.R"
